name: Deploy
on:
  push:
    branches:
      - 'master'

jobs:
  DeployToAmazon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node v20.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.11.0'

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          npm install -g aws-cli
          aws s3 sync dist/assets dist/favicon.ico dist/index.html s3://$S3_BUCKET_NAME --delete
